language: python
python: 3.7
dist: xenial

jobs:
  include:
    - name: main-pipeline

install:
  - "sudo apt update -y"
  - "sudo apt install python3-pip"
  - "sudo pip install pipenv"
  - "pipenv sync -d"

script:
  - "make check-format"
  - "make test"
  - "make build"