version: '3'

services:

    bot:
        image: effprime/basement-bot
        container_name: basement_bot
        build: .
        env_file: .env
        depends_on:
            - db

    db:
        image: postgres:12.0-alpine
        container_name: basement_bot_db
        volumes:
            - ./db:/var/lib/postgresql/data/
        env_file: .env